{
    "openapi": "3.0.1",
    "info": {
        "version": "1.0",
        "title": "Hangar API",
        "description": "This page describes the format for the current Hangar REST API as well as general usage guidelines.\u003Cbr\u003E\nNote that all routes **not** listed here should be considered **internal**, and can change at a moment's notice. **Do not use them**.\n\n## Authentication and Authorization\nThere are two ways to consume the API: Authenticated or anonymous.\n\n### Anonymous\nWhen using anonymous authentication, you only have access to public information, but you don't need to[...]"
    },
    "servers": [
        {
            "url": "https://hangar.papermc.io",
            "description": "Generated server url"
        }
    ],
    "paths": {
        "/api/v1/projects/{slug}/upload": {
            "post": {
                "tags": [
                    "Versions"
                ],
                "summary": "Creates a new version and returns parts of its metadata",
                "description": "Creates a new version for a project. Requires the `create_version` permission in the project or owning organization.\nMake sure you provide the contents of this request as multipart/form-data.\nYou can find a simple example implementation written in Java here: https://gist.github.com/kennytv/a227d82249f54e0ad35005330256fee2",
                "operationId": "uploadVersion",
                "security": [
                    {
                        "HangarAuth": [
                            "create_version"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{author}/{slug}/upload": {
            "post": {
                "tags": [
                    "Versions"
                ],
                "operationId": "uploadVersion_1",
                "deprecated": true
            }
        },
        "/api/v1/keys": {
            "get": {
                "tags": [
                    "API Keys"
                ],
                "summary": "Fetches a list of API Keys",
                "description": "Fetches a list of API Keys. Requires the `edit_api_keys` permission.",
                "operationId": "getKeys",
                "security": [
                    {
                        "HangarAuth": [
                            "edit_api_keys"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "API Keys"
                ],
                "summary": "Creates an API key",
                "description": "Creates an API key. Requires the `edit_api_keys` permission.",
                "operationId": "createKey",
                "security": [
                    {
                        "HangarAuth": [
                            "edit_api_keys"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "API Keys"
                ],
                "summary": "Deletes an API key",
                "description": "Deletes an API key. Requires the `edit_api_keys` permission.",
                "operationId": "deleteKey",
                "security": [
                    {
                        "HangarAuth": [
                            "edit_api_keys"
                        ]
                    }
                ]
            }
        },
        "/api/v1/authenticate": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Creates an API JWT",
                "description": "`Log-in` with your API key in order to be able to call other endpoints authenticated. The returned JWT should be specified as a header in all following requests: `Authorization: HangarAuth your.jwt`",
                "operationId": "authenticate"
            }
        },
        "/api/v1/pages/editmain/{slug}": {
            "patch": {
                "tags": [
                    "Pages"
                ],
                "summary": "Edits the main page of a project",
                "description": "Edits the main page of a project. Requires the `edit_page` permission in the project or owning organization.",
                "operationId": "editMainPage",
                "security": [
                    {
                        "HangarAuth": [
                            "edit_page"
                        ]
                    }
                ]
            }
        },
        "/api/v1/pages/edit/{slug}": {
            "patch": {
                "tags": [
                    "Pages"
                ],
                "summary": "Edits a page of a project",
                "description": "Edits a page of a project. Requires the `edit_page` permission in the project or owning organization.",
                "operationId": "editPage",
                "security": [
                    {
                        "HangarAuth": [
                            "edit_page"
                        ]
                    }
                ]
            }
        },
        "/api/v1/users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Searches for users",
                "description": "Returns a list of users based on a search query. Requires the `view_public_info` permission.",
                "operationId": "showUsers",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/users/{user}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns a specific user",
                "description": "Returns a specific user. Requires the `view_public_info` permission.",
                "operationId": "getUser",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/users/{user}/watching": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns the watched projects for a specific user",
                "description": "Returns the watched projects for a specific user. Requires the `view_public_info` permission.",
                "operationId": "getUserWatching",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/users/{user}/starred": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns the starred projects for a specific user",
                "description": "Returns the starred projects for a specific user. Requires the `view_public_info` permission.",
                "operationId": "showStarred",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/users/{user}/pinned": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns the pinned projects for a specific user",
                "description": "Returns the pinned projects for a specific user. Requires the `view_public_info` permission.",
                "operationId": "getUserPinnedProjects",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/staff": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns Hangar staff",
                "description": "Returns Hanagr staff. Requires the `view_public_info` permission.",
                "operationId": "getStaff",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects": {
            "get": {
                "tags": [
                    "Projects"
                ],
                "summary": "Searches the projects on Hangar",
                "description": "Searches all the projects on Hangar, or for a single user. Requires the `view_public_info` permission.",
                "operationId": "getProjects",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}": {
            "get": {
                "tags": [
                    "Projects"
                ],
                "summary": "Returns info on a specific project",
                "description": "Returns info on a specific project. Requires the `view_public_info` permission.",
                "operationId": "getProject",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/watchers": {
            "get": {
                "tags": [
                    "Projects"
                ],
                "summary": "Returns the watchers of a project",
                "description": "Returns the watchers of a project. Requires the `view_public_info` permission.",
                "operationId": "getProjectWatchers",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/versions": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "summary": "Returns all versions of a project",
                "description": "Returns all versions of a project. Requires the `view_public_info` permission in the project or owning organization.",
                "operationId": "listVersions",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/versions/{name}": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "summary": "Returns a specific version of a project",
                "description": "Returns a specific version of a project. Requires the `view_public_info` permission in the project or owning organization.",
                "operationId": "showVersion",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/versions/{name}/{platform}/download": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "summary": "Downloads a version",
                "description": "Downloads the file for a specific platform of a version. Requires visibility of the project and version.",
                "operationId": "downloadVersion",
                "security": [
                    {
                        "HangarAuth": [

                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/versions/{name}/stats": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "summary": "Returns the stats for a version",
                "description": "Returns the stats (downloads) for a version per day for a certain date range. Requires the `is_subject_member` permission.",
                "operationId": "showVersionStats",
                "security": [
                    {
                        "HangarAuth": [
                            "is_subject_member"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/stats": {
            "get": {
                "tags": [
                    "Projects"
                ],
                "summary": "Returns the stats for a project",
                "description": "Returns the stats (downloads and views) for a project per day for a certain date range. Requires the `is_subject_member` permission.",
                "operationId": "showProjectStats",
                "security": [
                    {
                        "HangarAuth": [
                            "is_subject_member"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/stargazers": {
            "get": {
                "tags": [
                    "Projects"
                ],
                "summary": "Returns the stargazers of a project",
                "description": "Returns the stargazers of a project. Requires the `view_public_info` permission.",
                "operationId": "getProjectStargazers",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/members": {
            "get": {
                "tags": [
                    "Projects"
                ],
                "summary": "Returns the members of a project",
                "description": "Returns the members of a project. Requires the `view_public_info` permission.",
                "operationId": "getProjectMembers",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/latestrelease": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "summary": "Returns the latest release version of a project",
                "description": "Returns the latest version of a project. Requires the `view_public_info` permission in the project or owning organizations.",
                "operationId": "latestReleaseVersion",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{slug}/latest": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "summary": "Returns the latest version of a project for a specific channel",
                "description": "Returns the latest version of a project. Requires the `view_public_info` permission in the project or owning organization.",
                "operationId": "latestVersion",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        },
        "/api/v1/projects/{author}/{slug}/versions": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "operationId": "getVersions",
                "deprecated": true
            }
        },
        "/api/v1/projects/{author}/{slug}/versions/{name}": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "operationId": "getVersion",
                "deprecated": true
            }
        },
        "/api/v1/projects/{author}/{slug}/versions/{name}/{platform}/download": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "operationId": "downloadVersion_1",
                "deprecated": true
            }
        },
        "/api/v1/projects/{author}/{slug}/versions/{name}/stats": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "operationId": "getVersionStats",
                "deprecated": true
            }
        },
        "/api/v1/projects/{author}/{slug}/latestrelease": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "operationId": "getLatestReleaseVersion",
                "deprecated": true
            }
        },
        "/api/v1/projects/{author}/{slug}/latest": {
            "get": {
                "tags": [
                    "Versions"
                ],
                "operationId": "getLatestVersion",
                "deprecated": true
            }
        },
        "/api/v1/permissions": {
            "get": {
                "tags": [
                    "Permissions"
                ],
                "summary": "Returns your permissions",
                "description": "Returns a list of permissions you have in the given context",
                "operationId": "showPermissions",
                "security": [
                    {
                        "HangarAuth": [

                        ]
                    }
                ]
            }
        },
        "/api/v1/permissions/hasAny": {
            "get": {
                "tags": [
                    "Permissions"
                ],
                "summary": "Checks whether you have at least one of the provided permissions",
                "description": "Checks whether you have at least one of the provided permissions in the given context",
                "operationId": "hasAny",
                "security": [
                    {
                        "HangarAuth": [

                        ]
                    }
                ]
            }
        },
        "/api/v1/permissions/hasAll": {
            "get": {
                "tags": [
                    "Permissions"
                ],
                "summary": "Checks whether you have all the provided permissions",
                "description": "Checks whether you have all the provided permissions in the given context",
                "operationId": "hasAll",
                "security": [
                    {
                        "HangarAuth": [

                        ]
                    }
                ]
            }
        },
        "/api/v1/pages/page/{slug}": {
            "get": {
                "tags": [
                    "Pages"
                ],
                "summary": "Returns a page of a project",
                "description": "Returns a page of a project. Requires visibility of the page.",
                "operationId": "getPage"
            }
        },
        "/api/v1/pages/main/{slug}": {
            "get": {
                "tags": [
                    "Pages"
                ],
                "summary": "Returns the main page of a project",
                "description": "Returns the main page of a project. Requires visibility of the page.",
                "operationId": "getMainPage"
            }
        },
        "/api/v1/authors": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns all users with at least one public project",
                "description": "Returns all users that have at least one public project. Requires the `view_public_info` permission.",
                "operationId": "getAuthors",
                "security": [
                    {
                        "HangarAuth": [
                            "view_public_info"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "HangarAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
